#
#  Created by Jeremy on 2015-08-08.
#  Copyright 2015. All rights reserved.  
#

TARGET := m3e

CFLAGS += -D_LINUX 
CFLAGS += -DHAVE_PTHREADS

LIBS += -lpthread -ldl
EXT_LIB += ./lib/libmp3lame.a

-include ../cfg/cfg_src.mk
-include ../cfg/cfg_rule.mk


