
# include
include_directories(AFTER ${M3E_SOURCE_DIR}/src/hardware/interfaces/configstore/utils/include)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/cas/1.0/android.hardware.cas@1.0_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/cas/native/1.0/android.hardware.cas.native@1.0_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/configstore/1.0/android.hardware.configstore@1.0_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/configstore/1.1/android.hardware.configstore@1.1_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/graphics/allocator/2.0/android.hardware.graphics.allocator@2.0_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/graphics/mapper/2.0/android.hardware.graphics.mapper@2.0_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/graphics/mapper/2.1/android.hardware.graphics.mapper@2.1_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/graphics/common/1.0/android.hardware.graphics.common@1.0_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/graphics/common/1.1/android.hardware.graphics.common@1.1_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/graphics/bufferqueue/1.0/android.hardware.graphics.bufferqueue@1.0_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/graphics/composer/2.1/android.hardware.graphics.composer@2.1_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/graphics/composer/2.2/android.hardware.graphics.composer@2.2_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/media/1.0/android.hardware.media@1.0_genc++_headers/gen)
include_directories(AFTER ${M3E_SOURCE_DIR}/src/intermediate/hardware/interfaces/media/omx/1.0/android.hardware.media.omx@1.0_genc++_headers/gen)
